# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8a5b354e6631c8f35af52d562117c736"
application_url = "https://idea-letters-nascar-vertex.trycloudflare.com"
embedded = true
name = "test-shweta-app"
handle = "test-shweta-app"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://idea-letters-nascar-vertex.trycloudflare.com/auth/callback",
  "https://idea-letters-nascar-vertex.trycloudflare.com/auth/shopify/callback",
  "https://idea-letters-nascar-vertex.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
